version: '3.8'

services:
  aigerus-backend:
    image: aigerus-backend:latest
    container_name: aigerus-backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/aigerus-backend/.env
