version: '3.8'

services:
  aigerus-backend:
    image: aigerus-backend:latest
    container_name: aigerus-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb+srv://ruslanamirovit:c5bvgWT4Ik7SEpH2@cluster0.bg8sv1a.mongodb.net/aigerus
      - PORT=3000
      - R2_ACCOUNT_ID=your-r2-account-id
      - R2_ACCESS_KEY_ID=your-r2-access-key-id
      - R2_SECRET_ACCESS_KEY=your-r2-secret-access-key
      - R2_BUCKET_NAME=your-r2-bucket-name
      - NODE_ENV=production
