version: '3.8'

services:
  aigerus-backend:
    image: aigerus-backend:latest
    container_name: aigerus-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb+srv://ruslanamirovit:c5bvgWT4Ik7SEpH2@cluster0.bg8sv1a.mongodb.net/aigerus
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=3000
      - NODE_ENV=production
